// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBdJj0dZImJwYdQCCvJ1d_zo8PfQuonqg',
    appId: '1:243306841250:web:b79f43c02e7c8a6a02c3fb',
    messagingSenderId: '243306841250',
    projectId: 'river-cycle-606',
    authDomain: 'river-cycle-606.firebaseapp.com',
    databaseURL: 'https://river-cycle-606.firebaseio.com',
    storageBucket: 'river-cycle-606.appspot.com',
    measurementId: 'G-03P4755GK2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6CBIa-xaSEItZwdXl5VURS8CEv6gR4c4',
    appId: '1:243306841250:android:7f810b10a7e40fb402c3fb',
    messagingSenderId: '243306841250',
    projectId: 'river-cycle-606',
    databaseURL: 'https://river-cycle-606.firebaseio.com',
    storageBucket: 'river-cycle-606.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADd6TEMmCz6ltYF5ZBO1zEDEURTsCuNUw',
    appId: '1:243306841250:ios:1720c46ff2bc49f802c3fb',
    messagingSenderId: '243306841250',
    projectId: 'river-cycle-606',
    databaseURL: 'https://river-cycle-606.firebaseio.com',
    storageBucket: 'river-cycle-606.appspot.com',
    androidClientId: '243306841250-cqbqitrr99kke5t47vg9k9730su4c402.apps.googleusercontent.com',
    iosClientId: '243306841250-0446d4ghfokin76ekbdetgnhj3p6s4t6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterBlocFirestoreSampleApp',
  );
}
